// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/mempool/types.proto

package mempool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Txs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           [][]byte               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Txs) Reset() {
	*x = Txs{}
	mi := &file_tendermint_mempool_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Txs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txs) ProtoMessage() {}

func (x *Txs) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_mempool_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txs.ProtoReflect.Descriptor instead.
func (*Txs) Descriptor() ([]byte, []int) {
	return file_tendermint_mempool_types_proto_rawDescGZIP(), []int{0}
}

func (x *Txs) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sum:
	//
	//	*Message_Txs
	Sum           isMessage_Sum `protobuf_oneof:"sum"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_tendermint_mempool_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_mempool_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_tendermint_mempool_types_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetSum() isMessage_Sum {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *Message) GetTxs() *Txs {
	if x != nil {
		if x, ok := x.Sum.(*Message_Txs); ok {
			return x.Txs
		}
	}
	return nil
}

type isMessage_Sum interface {
	isMessage_Sum()
}

type Message_Txs struct {
	Txs *Txs `protobuf:"bytes,1,opt,name=txs,proto3,oneof"`
}

func (*Message_Txs) isMessage_Sum() {}

var File_tendermint_mempool_types_proto protoreflect.FileDescriptor

const file_tendermint_mempool_types_proto_rawDesc = "" +
	"\n" +
	"\x1etendermint/mempool/types.proto\x12\x12tendermint.mempool\"\x17\n" +
	"\x03Txs\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\"=\n" +
	"\aMessage\x12+\n" +
	"\x03txs\x18\x01 \x01(\v2\x17.tendermint.mempool.TxsH\x00R\x03txsB\x05\n" +
	"\x03sumB\xca\x01\n" +
	"\x16com.tendermint.mempoolB\n" +
	"TypesProtoP\x01Z;github.com/fluentum-chain/fluentum/proto/tendermint/mempool\xa2\x02\x03TMX\xaa\x02\x12Tendermint.Mempool\xca\x02\x12Tendermint\\Mempool\xe2\x02\x1eTendermint\\Mempool\\GPBMetadata\xea\x02\x13Tendermint::Mempoolb\x06proto3"

var (
	file_tendermint_mempool_types_proto_rawDescOnce sync.Once
	file_tendermint_mempool_types_proto_rawDescData []byte
)

func file_tendermint_mempool_types_proto_rawDescGZIP() []byte {
	file_tendermint_mempool_types_proto_rawDescOnce.Do(func() {
		file_tendermint_mempool_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_mempool_types_proto_rawDesc), len(file_tendermint_mempool_types_proto_rawDesc)))
	})
	return file_tendermint_mempool_types_proto_rawDescData
}

var file_tendermint_mempool_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tendermint_mempool_types_proto_goTypes = []any{
	(*Txs)(nil),     // 0: tendermint.mempool.Txs
	(*Message)(nil), // 1: tendermint.mempool.Message
}
var file_tendermint_mempool_types_proto_depIdxs = []int32{
	0, // 0: tendermint.mempool.Message.txs:type_name -> tendermint.mempool.Txs
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tendermint_mempool_types_proto_init() }
func file_tendermint_mempool_types_proto_init() {
	if File_tendermint_mempool_types_proto != nil {
		return
	}
	file_tendermint_mempool_types_proto_msgTypes[1].OneofWrappers = []any{
		(*Message_Txs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_mempool_types_proto_rawDesc), len(file_tendermint_mempool_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_mempool_types_proto_goTypes,
		DependencyIndexes: file_tendermint_mempool_types_proto_depIdxs,
		MessageInfos:      file_tendermint_mempool_types_proto_msgTypes,
	}.Build()
	File_tendermint_mempool_types_proto = out.File
	file_tendermint_mempool_types_proto_goTypes = nil
	file_tendermint_mempool_types_proto_depIdxs = nil
}
