version: '3.8'

services:
  fluentum-validator:
    build:
      context: .
      dockerfile: Dockerfile
    image: fluentum/validator:latest
    container_name: fluentum-validator
    restart: unless-stopped
    environment:
      - MONIKER=validator1
      - CHAIN_ID=fluentum-1
      - SEED_NODES=seed1.fluentum.net:26656,seed2.fluentum.net:26656
      - ZK_PROVER_URL=https://zk.fluentum.net
    volumes:
      - ./config:/fluentum/config
      - ./quantum-keys:/quantum-keys
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "26660:26660"  # Prometheus
    networks:
      - fluentum-net

  fluentum-sentry:
    build:
      context: .
      dockerfile: Dockerfile
    image: fluentum/sentry:latest
    container_name: fluentum-sentry
    restart: unless-stopped
    environment:
      - MONIKER=sentry1
      - CHAIN_ID=fluentum-1
      - SEED_NODES=seed1.fluentum.net:26656,seed2.fluentum.net:26656
    volumes:
      - ./sentry-config:/fluentum/config
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "26660:26660"  # Prometheus
    networks:
      - fluentum-net

  cosmos-exporter:
    image: ghcr.io/solarlabsteam/cosmos-exporter:latest
    container_name: cosmos-exporter
    restart: unless-stopped
    environment:
      - VALIDATOR_ADDR=fluentum-validator:26657
    ports:
      - "9300:9300"
    networks:
      - fluentum-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - fluentum-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - fluentum-net

networks:
  fluentum-net:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:

