// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/types/block.proto

package types

import (
	_ "github.com/fluentum-chain/fluentum/proto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Evidence      *EvidenceList          `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	LastCommit    *Commit                `protobuf:"bytes,4,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_tendermint_types_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_types_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_tendermint_types_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetEvidence() *EvidenceList {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Block) GetLastCommit() *Commit {
	if x != nil {
		return x.LastCommit
	}
	return nil
}

var File_tendermint_types_block_proto protoreflect.FileDescriptor

const file_tendermint_types_block_proto_rawDesc = "" +
	"\n" +
	"\x1ctendermint/types/block.proto\x12\x10tendermint.types\x1a\x14gogoproto/gogo.proto\x1a\x1ctendermint/types/types.proto\x1a\x1ftendermint/types/evidence.proto\"\xee\x01\n" +
	"\x05Block\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x18.tendermint.types.HeaderB\x04\xc8\xde\x1f\x00R\x06header\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x16.tendermint.types.DataB\x04\xc8\xde\x1f\x00R\x04data\x12@\n" +
	"\bevidence\x18\x03 \x01(\v2\x1e.tendermint.types.EvidenceListB\x04\xc8\xde\x1f\x00R\bevidence\x129\n" +
	"\vlast_commit\x18\x04 \x01(\v2\x18.tendermint.types.CommitR\n" +
	"lastCommitB\xbe\x01\n" +
	"\x14com.tendermint.typesB\n" +
	"BlockProtoP\x01Z9github.com/fluentum-chain/fluentum/proto/tendermint/types\xa2\x02\x03TTX\xaa\x02\x10Tendermint.Types\xca\x02\x10Tendermint\\Types\xe2\x02\x1cTendermint\\Types\\GPBMetadata\xea\x02\x11Tendermint::Typesb\x06proto3"

var (
	file_tendermint_types_block_proto_rawDescOnce sync.Once
	file_tendermint_types_block_proto_rawDescData []byte
)

func file_tendermint_types_block_proto_rawDescGZIP() []byte {
	file_tendermint_types_block_proto_rawDescOnce.Do(func() {
		file_tendermint_types_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_types_block_proto_rawDesc), len(file_tendermint_types_block_proto_rawDesc)))
	})
	return file_tendermint_types_block_proto_rawDescData
}

var file_tendermint_types_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tendermint_types_block_proto_goTypes = []any{
	(*Block)(nil),        // 0: tendermint.types.Block
	(*Header)(nil),       // 1: tendermint.types.Header
	(*Data)(nil),         // 2: tendermint.types.Data
	(*EvidenceList)(nil), // 3: tendermint.types.EvidenceList
	(*Commit)(nil),       // 4: tendermint.types.Commit
}
var file_tendermint_types_block_proto_depIdxs = []int32{
	1, // 0: tendermint.types.Block.header:type_name -> tendermint.types.Header
	2, // 1: tendermint.types.Block.data:type_name -> tendermint.types.Data
	3, // 2: tendermint.types.Block.evidence:type_name -> tendermint.types.EvidenceList
	4, // 3: tendermint.types.Block.last_commit:type_name -> tendermint.types.Commit
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tendermint_types_block_proto_init() }
func file_tendermint_types_block_proto_init() {
	if File_tendermint_types_block_proto != nil {
		return
	}
	file_tendermint_types_types_proto_init()
	file_tendermint_types_evidence_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_types_block_proto_rawDesc), len(file_tendermint_types_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_types_block_proto_goTypes,
		DependencyIndexes: file_tendermint_types_block_proto_depIdxs,
		MessageInfos:      file_tendermint_types_block_proto_msgTypes,
	}.Build()
	File_tendermint_types_block_proto = out.File
	file_tendermint_types_block_proto_goTypes = nil
	file_tendermint_types_block_proto_depIdxs = nil
}
