// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/types/canonical.proto

package types

import (
	_ "github.com/fluentum-chain/fluentum/proto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanonicalBlockID struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Hash          []byte                  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PartSetHeader *CanonicalPartSetHeader `protobuf:"bytes,2,opt,name=part_set_header,json=partSetHeader,proto3" json:"part_set_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalBlockID) Reset() {
	*x = CanonicalBlockID{}
	mi := &file_tendermint_types_canonical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalBlockID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalBlockID) ProtoMessage() {}

func (x *CanonicalBlockID) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_types_canonical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalBlockID.ProtoReflect.Descriptor instead.
func (*CanonicalBlockID) Descriptor() ([]byte, []int) {
	return file_tendermint_types_canonical_proto_rawDescGZIP(), []int{0}
}

func (x *CanonicalBlockID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CanonicalBlockID) GetPartSetHeader() *CanonicalPartSetHeader {
	if x != nil {
		return x.PartSetHeader
	}
	return nil
}

type CanonicalPartSetHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalPartSetHeader) Reset() {
	*x = CanonicalPartSetHeader{}
	mi := &file_tendermint_types_canonical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalPartSetHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalPartSetHeader) ProtoMessage() {}

func (x *CanonicalPartSetHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_types_canonical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalPartSetHeader.ProtoReflect.Descriptor instead.
func (*CanonicalPartSetHeader) Descriptor() ([]byte, []int) {
	return file_tendermint_types_canonical_proto_rawDescGZIP(), []int{1}
}

func (x *CanonicalPartSetHeader) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CanonicalPartSetHeader) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type CanonicalProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SignedMsgType          `protobuf:"varint,1,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"` // type alias for byte
	Height        int64                  `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`                                // canonicalization requires fixed size encoding here
	Round         int64                  `protobuf:"fixed64,3,opt,name=round,proto3" json:"round,omitempty"`                                  // canonicalization requires fixed size encoding here
	PolRound      int64                  `protobuf:"varint,4,opt,name=pol_round,json=polRound,proto3" json:"pol_round,omitempty"`
	BlockId       *CanonicalBlockID      `protobuf:"bytes,5,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId       string                 `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalProposal) Reset() {
	*x = CanonicalProposal{}
	mi := &file_tendermint_types_canonical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalProposal) ProtoMessage() {}

func (x *CanonicalProposal) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_types_canonical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalProposal.ProtoReflect.Descriptor instead.
func (*CanonicalProposal) Descriptor() ([]byte, []int) {
	return file_tendermint_types_canonical_proto_rawDescGZIP(), []int{2}
}

func (x *CanonicalProposal) GetType() SignedMsgType {
	if x != nil {
		return x.Type
	}
	return SignedMsgType_SIGNED_MSG_TYPE_UNKNOWN
}

func (x *CanonicalProposal) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CanonicalProposal) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CanonicalProposal) GetPolRound() int64 {
	if x != nil {
		return x.PolRound
	}
	return 0
}

func (x *CanonicalProposal) GetBlockId() *CanonicalBlockID {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *CanonicalProposal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CanonicalProposal) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type CanonicalVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SignedMsgType          `protobuf:"varint,1,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"` // type alias for byte
	Height        int64                  `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`                                // canonicalization requires fixed size encoding here
	Round         int64                  `protobuf:"fixed64,3,opt,name=round,proto3" json:"round,omitempty"`                                  // canonicalization requires fixed size encoding here
	BlockId       *CanonicalBlockID      `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId       string                 `protobuf:"bytes,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanonicalVote) Reset() {
	*x = CanonicalVote{}
	mi := &file_tendermint_types_canonical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalVote) ProtoMessage() {}

func (x *CanonicalVote) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_types_canonical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalVote.ProtoReflect.Descriptor instead.
func (*CanonicalVote) Descriptor() ([]byte, []int) {
	return file_tendermint_types_canonical_proto_rawDescGZIP(), []int{3}
}

func (x *CanonicalVote) GetType() SignedMsgType {
	if x != nil {
		return x.Type
	}
	return SignedMsgType_SIGNED_MSG_TYPE_UNKNOWN
}

func (x *CanonicalVote) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CanonicalVote) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CanonicalVote) GetBlockId() *CanonicalBlockID {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *CanonicalVote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CanonicalVote) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

var File_tendermint_types_canonical_proto protoreflect.FileDescriptor

const file_tendermint_types_canonical_proto_rawDesc = "" +
	"\n" +
	" tendermint/types/canonical.proto\x12\x10tendermint.types\x1a\x14gogoproto/gogo.proto\x1a\x1ctendermint/types/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\x10CanonicalBlockID\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12V\n" +
	"\x0fpart_set_header\x18\x02 \x01(\v2(.tendermint.types.CanonicalPartSetHeaderB\x04\xc8\xde\x1f\x00R\rpartSetHeader\"B\n" +
	"\x16CanonicalPartSetHeader\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"\xd9\x02\n" +
	"\x11CanonicalProposal\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.tendermint.types.SignedMsgTypeR\x04type\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x10R\x06height\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x10R\x05round\x12)\n" +
	"\tpol_round\x18\x04 \x01(\x03B\f\xe2\xde\x1f\bPOLRoundR\bpolRound\x12J\n" +
	"\bblock_id\x18\x05 \x01(\v2\".tendermint.types.CanonicalBlockIDB\v\xe2\xde\x1f\aBlockIDR\ablockId\x12B\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\ttimestamp\x12&\n" +
	"\bchain_id\x18\a \x01(\tB\v\xe2\xde\x1f\aChainIDR\achainId\"\xaa\x02\n" +
	"\rCanonicalVote\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.tendermint.types.SignedMsgTypeR\x04type\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x10R\x06height\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x10R\x05round\x12J\n" +
	"\bblock_id\x18\x04 \x01(\v2\".tendermint.types.CanonicalBlockIDB\v\xe2\xde\x1f\aBlockIDR\ablockId\x12B\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\ttimestamp\x12&\n" +
	"\bchain_id\x18\x06 \x01(\tB\v\xe2\xde\x1f\aChainIDR\achainIdB\xc2\x01\n" +
	"\x14com.tendermint.typesB\x0eCanonicalProtoP\x01Z9github.com/fluentum-chain/fluentum/proto/tendermint/types\xa2\x02\x03TTX\xaa\x02\x10Tendermint.Types\xca\x02\x10Tendermint\\Types\xe2\x02\x1cTendermint\\Types\\GPBMetadata\xea\x02\x11Tendermint::Typesb\x06proto3"

var (
	file_tendermint_types_canonical_proto_rawDescOnce sync.Once
	file_tendermint_types_canonical_proto_rawDescData []byte
)

func file_tendermint_types_canonical_proto_rawDescGZIP() []byte {
	file_tendermint_types_canonical_proto_rawDescOnce.Do(func() {
		file_tendermint_types_canonical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_types_canonical_proto_rawDesc), len(file_tendermint_types_canonical_proto_rawDesc)))
	})
	return file_tendermint_types_canonical_proto_rawDescData
}

var file_tendermint_types_canonical_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tendermint_types_canonical_proto_goTypes = []any{
	(*CanonicalBlockID)(nil),       // 0: tendermint.types.CanonicalBlockID
	(*CanonicalPartSetHeader)(nil), // 1: tendermint.types.CanonicalPartSetHeader
	(*CanonicalProposal)(nil),      // 2: tendermint.types.CanonicalProposal
	(*CanonicalVote)(nil),          // 3: tendermint.types.CanonicalVote
	(SignedMsgType)(0),             // 4: tendermint.types.SignedMsgType
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_tendermint_types_canonical_proto_depIdxs = []int32{
	1, // 0: tendermint.types.CanonicalBlockID.part_set_header:type_name -> tendermint.types.CanonicalPartSetHeader
	4, // 1: tendermint.types.CanonicalProposal.type:type_name -> tendermint.types.SignedMsgType
	0, // 2: tendermint.types.CanonicalProposal.block_id:type_name -> tendermint.types.CanonicalBlockID
	5, // 3: tendermint.types.CanonicalProposal.timestamp:type_name -> google.protobuf.Timestamp
	4, // 4: tendermint.types.CanonicalVote.type:type_name -> tendermint.types.SignedMsgType
	0, // 5: tendermint.types.CanonicalVote.block_id:type_name -> tendermint.types.CanonicalBlockID
	5, // 6: tendermint.types.CanonicalVote.timestamp:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tendermint_types_canonical_proto_init() }
func file_tendermint_types_canonical_proto_init() {
	if File_tendermint_types_canonical_proto != nil {
		return
	}
	file_tendermint_types_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_types_canonical_proto_rawDesc), len(file_tendermint_types_canonical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_types_canonical_proto_goTypes,
		DependencyIndexes: file_tendermint_types_canonical_proto_depIdxs,
		MessageInfos:      file_tendermint_types_canonical_proto_msgTypes,
	}.Build()
	File_tendermint_types_canonical_proto = out.File
	file_tendermint_types_canonical_proto_goTypes = nil
	file_tendermint_types_canonical_proto_depIdxs = nil
}
