// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/types/events.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventDataRoundState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step          string                 `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDataRoundState) Reset() {
	*x = EventDataRoundState{}
	mi := &file_tendermint_types_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDataRoundState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDataRoundState) ProtoMessage() {}

func (x *EventDataRoundState) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_types_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDataRoundState.ProtoReflect.Descriptor instead.
func (*EventDataRoundState) Descriptor() ([]byte, []int) {
	return file_tendermint_types_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventDataRoundState) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *EventDataRoundState) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *EventDataRoundState) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

var File_tendermint_types_events_proto protoreflect.FileDescriptor

const file_tendermint_types_events_proto_rawDesc = "" +
	"\n" +
	"\x1dtendermint/types/events.proto\x12\x10tendermint.types\"W\n" +
	"\x13EventDataRoundState\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12\x12\n" +
	"\x04step\x18\x03 \x01(\tR\x04stepB\xbf\x01\n" +
	"\x14com.tendermint.typesB\vEventsProtoP\x01Z9github.com/fluentum-chain/fluentum/proto/tendermint/types\xa2\x02\x03TTX\xaa\x02\x10Tendermint.Types\xca\x02\x10Tendermint\\Types\xe2\x02\x1cTendermint\\Types\\GPBMetadata\xea\x02\x11Tendermint::Typesb\x06proto3"

var (
	file_tendermint_types_events_proto_rawDescOnce sync.Once
	file_tendermint_types_events_proto_rawDescData []byte
)

func file_tendermint_types_events_proto_rawDescGZIP() []byte {
	file_tendermint_types_events_proto_rawDescOnce.Do(func() {
		file_tendermint_types_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_types_events_proto_rawDesc), len(file_tendermint_types_events_proto_rawDesc)))
	})
	return file_tendermint_types_events_proto_rawDescData
}

var file_tendermint_types_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tendermint_types_events_proto_goTypes = []any{
	(*EventDataRoundState)(nil), // 0: tendermint.types.EventDataRoundState
}
var file_tendermint_types_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tendermint_types_events_proto_init() }
func file_tendermint_types_events_proto_init() {
	if File_tendermint_types_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_types_events_proto_rawDesc), len(file_tendermint_types_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_types_events_proto_goTypes,
		DependencyIndexes: file_tendermint_types_events_proto_depIdxs,
		MessageInfos:      file_tendermint_types_events_proto_msgTypes,
	}.Build()
	File_tendermint_types_events_proto = out.File
	file_tendermint_types_events_proto_goTypes = nil
	file_tendermint_types_events_proto_depIdxs = nil
}
