// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/rpc/grpc/types.proto

package grpc

import (
	abci "github.com/fluentum-chain/fluentum/proto/tendermint/abci"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPing) Reset() {
	*x = RequestPing{}
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPing) ProtoMessage() {}

func (x *RequestPing) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPing.ProtoReflect.Descriptor instead.
func (*RequestPing) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{0}
}

type RequestBroadcastTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBroadcastTx) Reset() {
	*x = RequestBroadcastTx{}
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBroadcastTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBroadcastTx) ProtoMessage() {}

func (x *RequestBroadcastTx) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBroadcastTx.ProtoReflect.Descriptor instead.
func (*RequestBroadcastTx) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{1}
}

func (x *RequestBroadcastTx) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

type ResponsePing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePing) Reset() {
	*x = ResponsePing{}
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePing) ProtoMessage() {}

func (x *ResponsePing) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePing.ProtoReflect.Descriptor instead.
func (*ResponsePing) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{2}
}

type ResponseBroadcastTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckTx       *abci.ResponseCheckTx  `protobuf:"bytes,1,opt,name=check_tx,json=checkTx,proto3" json:"check_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBroadcastTx) Reset() {
	*x = ResponseBroadcastTx{}
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBroadcastTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBroadcastTx) ProtoMessage() {}

func (x *ResponseBroadcastTx) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_rpc_grpc_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBroadcastTx.ProtoReflect.Descriptor instead.
func (*ResponseBroadcastTx) Descriptor() ([]byte, []int) {
	return file_tendermint_rpc_grpc_types_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseBroadcastTx) GetCheckTx() *abci.ResponseCheckTx {
	if x != nil {
		return x.CheckTx
	}
	return nil
}

var File_tendermint_rpc_grpc_types_proto protoreflect.FileDescriptor

const file_tendermint_rpc_grpc_types_proto_rawDesc = "" +
	"\n" +
	"\x1ftendermint/rpc/grpc/types.proto\x12\x13tendermint.rpc.grpc\x1a\x1btendermint/abci/types.proto\"\r\n" +
	"\vRequestPing\"$\n" +
	"\x12RequestBroadcastTx\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02tx\"\x0e\n" +
	"\fResponsePing\"R\n" +
	"\x13ResponseBroadcastTx\x12;\n" +
	"\bcheck_tx\x18\x01 \x01(\v2 .tendermint.abci.ResponseCheckTxR\acheckTx2\xbd\x01\n" +
	"\fBroadcastAPI\x12K\n" +
	"\x04Ping\x12 .tendermint.rpc.grpc.RequestPing\x1a!.tendermint.rpc.grpc.ResponsePing\x12`\n" +
	"\vBroadcastTx\x12'.tendermint.rpc.grpc.RequestBroadcastTx\x1a(.tendermint.rpc.grpc.ResponseBroadcastTxB\xd1\x01\n" +
	"\x17com.tendermint.rpc.grpcB\n" +
	"TypesProtoP\x01Z<github.com/fluentum-chain/fluentum/proto/tendermint/rpc/grpc\xa2\x02\x03TRG\xaa\x02\x13Tendermint.Rpc.Grpc\xca\x02\x13Tendermint\\Rpc\\Grpc\xe2\x02\x1fTendermint\\Rpc\\Grpc\\GPBMetadata\xea\x02\x15Tendermint::Rpc::Grpcb\x06proto3"

var (
	file_tendermint_rpc_grpc_types_proto_rawDescOnce sync.Once
	file_tendermint_rpc_grpc_types_proto_rawDescData []byte
)

func file_tendermint_rpc_grpc_types_proto_rawDescGZIP() []byte {
	file_tendermint_rpc_grpc_types_proto_rawDescOnce.Do(func() {
		file_tendermint_rpc_grpc_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_rpc_grpc_types_proto_rawDesc), len(file_tendermint_rpc_grpc_types_proto_rawDesc)))
	})
	return file_tendermint_rpc_grpc_types_proto_rawDescData
}

var file_tendermint_rpc_grpc_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tendermint_rpc_grpc_types_proto_goTypes = []any{
	(*RequestPing)(nil),          // 0: tendermint.rpc.grpc.RequestPing
	(*RequestBroadcastTx)(nil),   // 1: tendermint.rpc.grpc.RequestBroadcastTx
	(*ResponsePing)(nil),         // 2: tendermint.rpc.grpc.ResponsePing
	(*ResponseBroadcastTx)(nil),  // 3: tendermint.rpc.grpc.ResponseBroadcastTx
	(*abci.ResponseCheckTx)(nil), // 4: tendermint.abci.ResponseCheckTx
}
var file_tendermint_rpc_grpc_types_proto_depIdxs = []int32{
	4, // 0: tendermint.rpc.grpc.ResponseBroadcastTx.check_tx:type_name -> tendermint.abci.ResponseCheckTx
	0, // 1: tendermint.rpc.grpc.BroadcastAPI.Ping:input_type -> tendermint.rpc.grpc.RequestPing
	1, // 2: tendermint.rpc.grpc.BroadcastAPI.BroadcastTx:input_type -> tendermint.rpc.grpc.RequestBroadcastTx
	2, // 3: tendermint.rpc.grpc.BroadcastAPI.Ping:output_type -> tendermint.rpc.grpc.ResponsePing
	3, // 4: tendermint.rpc.grpc.BroadcastAPI.BroadcastTx:output_type -> tendermint.rpc.grpc.ResponseBroadcastTx
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tendermint_rpc_grpc_types_proto_init() }
func file_tendermint_rpc_grpc_types_proto_init() {
	if File_tendermint_rpc_grpc_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_rpc_grpc_types_proto_rawDesc), len(file_tendermint_rpc_grpc_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tendermint_rpc_grpc_types_proto_goTypes,
		DependencyIndexes: file_tendermint_rpc_grpc_types_proto_depIdxs,
		MessageInfos:      file_tendermint_rpc_grpc_types_proto_msgTypes,
	}.Build()
	File_tendermint_rpc_grpc_types_proto = out.File
	file_tendermint_rpc_grpc_types_proto_goTypes = nil
	file_tendermint_rpc_grpc_types_proto_depIdxs = nil
}
