// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/privval/types.proto

package privval

import (
	_ "github.com/fluentum-chain/fluentum/proto/gogoproto"
	crypto "github.com/fluentum-chain/fluentum/proto/tendermint/crypto"
	types "github.com/fluentum-chain/fluentum/proto/tendermint/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Errors int32

const (
	Errors_ERRORS_UNKNOWN             Errors = 0
	Errors_ERRORS_UNEXPECTED_RESPONSE Errors = 1
	Errors_ERRORS_NO_CONNECTION       Errors = 2
	Errors_ERRORS_CONNECTION_TIMEOUT  Errors = 3
	Errors_ERRORS_READ_TIMEOUT        Errors = 4
	Errors_ERRORS_WRITE_TIMEOUT       Errors = 5
)

// Enum value maps for Errors.
var (
	Errors_name = map[int32]string{
		0: "ERRORS_UNKNOWN",
		1: "ERRORS_UNEXPECTED_RESPONSE",
		2: "ERRORS_NO_CONNECTION",
		3: "ERRORS_CONNECTION_TIMEOUT",
		4: "ERRORS_READ_TIMEOUT",
		5: "ERRORS_WRITE_TIMEOUT",
	}
	Errors_value = map[string]int32{
		"ERRORS_UNKNOWN":             0,
		"ERRORS_UNEXPECTED_RESPONSE": 1,
		"ERRORS_NO_CONNECTION":       2,
		"ERRORS_CONNECTION_TIMEOUT":  3,
		"ERRORS_READ_TIMEOUT":        4,
		"ERRORS_WRITE_TIMEOUT":       5,
	}
)

func (x Errors) Enum() *Errors {
	p := new(Errors)
	*p = x
	return p
}

func (x Errors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Errors) Descriptor() protoreflect.EnumDescriptor {
	return file_tendermint_privval_types_proto_enumTypes[0].Descriptor()
}

func (Errors) Type() protoreflect.EnumType {
	return &file_tendermint_privval_types_proto_enumTypes[0]
}

func (x Errors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Errors.Descriptor instead.
func (Errors) EnumDescriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{0}
}

type RemoteSignerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteSignerError) Reset() {
	*x = RemoteSignerError{}
	mi := &file_tendermint_privval_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteSignerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSignerError) ProtoMessage() {}

func (x *RemoteSignerError) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSignerError.ProtoReflect.Descriptor instead.
func (*RemoteSignerError) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteSignerError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoteSignerError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// PubKeyRequest requests the consensus public key from the remote signer.
type PubKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubKeyRequest) Reset() {
	*x = PubKeyRequest{}
	mi := &file_tendermint_privval_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyRequest) ProtoMessage() {}

func (x *PubKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyRequest.ProtoReflect.Descriptor instead.
func (*PubKeyRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{1}
}

func (x *PubKeyRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// PubKeyResponse is a response message containing the public key.
type PubKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        *crypto.PublicKey      `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Error         *RemoteSignerError     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubKeyResponse) Reset() {
	*x = PubKeyResponse{}
	mi := &file_tendermint_privval_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyResponse) ProtoMessage() {}

func (x *PubKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyResponse.ProtoReflect.Descriptor instead.
func (*PubKeyResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{2}
}

func (x *PubKeyResponse) GetPubKey() *crypto.PublicKey {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *PubKeyResponse) GetError() *RemoteSignerError {
	if x != nil {
		return x.Error
	}
	return nil
}

// SignVoteRequest is a request to sign a vote
type SignVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          *types.Vote            `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignVoteRequest) Reset() {
	*x = SignVoteRequest{}
	mi := &file_tendermint_privval_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignVoteRequest) ProtoMessage() {}

func (x *SignVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignVoteRequest.ProtoReflect.Descriptor instead.
func (*SignVoteRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{3}
}

func (x *SignVoteRequest) GetVote() *types.Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

func (x *SignVoteRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// SignedVoteResponse is a response containing a signed vote or an error
type SignedVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          *types.Vote            `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Error         *RemoteSignerError     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedVoteResponse) Reset() {
	*x = SignedVoteResponse{}
	mi := &file_tendermint_privval_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedVoteResponse) ProtoMessage() {}

func (x *SignedVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedVoteResponse.ProtoReflect.Descriptor instead.
func (*SignedVoteResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{4}
}

func (x *SignedVoteResponse) GetVote() *types.Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

func (x *SignedVoteResponse) GetError() *RemoteSignerError {
	if x != nil {
		return x.Error
	}
	return nil
}

// SignProposalRequest is a request to sign a proposal
type SignProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *types.Proposal        `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignProposalRequest) Reset() {
	*x = SignProposalRequest{}
	mi := &file_tendermint_privval_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignProposalRequest) ProtoMessage() {}

func (x *SignProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignProposalRequest.ProtoReflect.Descriptor instead.
func (*SignProposalRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{5}
}

func (x *SignProposalRequest) GetProposal() *types.Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *SignProposalRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// SignedProposalResponse is response containing a signed proposal or an error
type SignedProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *types.Proposal        `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Error         *RemoteSignerError     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedProposalResponse) Reset() {
	*x = SignedProposalResponse{}
	mi := &file_tendermint_privval_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedProposalResponse) ProtoMessage() {}

func (x *SignedProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedProposalResponse.ProtoReflect.Descriptor instead.
func (*SignedProposalResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{6}
}

func (x *SignedProposalResponse) GetProposal() *types.Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *SignedProposalResponse) GetError() *RemoteSignerError {
	if x != nil {
		return x.Error
	}
	return nil
}

// PingRequest is a request to confirm that the connection is alive.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_tendermint_privval_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{7}
}

// PingResponse is a response to confirm that the connection is alive.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_tendermint_privval_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{8}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sum:
	//
	//	*Message_PubKeyRequest
	//	*Message_PubKeyResponse
	//	*Message_SignVoteRequest
	//	*Message_SignedVoteResponse
	//	*Message_SignProposalRequest
	//	*Message_SignedProposalResponse
	//	*Message_PingRequest
	//	*Message_PingResponse
	Sum           isMessage_Sum `protobuf_oneof:"sum"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_tendermint_privval_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_privval_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_tendermint_privval_types_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetSum() isMessage_Sum {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *Message) GetPubKeyRequest() *PubKeyRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_PubKeyRequest); ok {
			return x.PubKeyRequest
		}
	}
	return nil
}

func (x *Message) GetPubKeyResponse() *PubKeyResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_PubKeyResponse); ok {
			return x.PubKeyResponse
		}
	}
	return nil
}

func (x *Message) GetSignVoteRequest() *SignVoteRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_SignVoteRequest); ok {
			return x.SignVoteRequest
		}
	}
	return nil
}

func (x *Message) GetSignedVoteResponse() *SignedVoteResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_SignedVoteResponse); ok {
			return x.SignedVoteResponse
		}
	}
	return nil
}

func (x *Message) GetSignProposalRequest() *SignProposalRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_SignProposalRequest); ok {
			return x.SignProposalRequest
		}
	}
	return nil
}

func (x *Message) GetSignedProposalResponse() *SignedProposalResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_SignedProposalResponse); ok {
			return x.SignedProposalResponse
		}
	}
	return nil
}

func (x *Message) GetPingRequest() *PingRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_PingRequest); ok {
			return x.PingRequest
		}
	}
	return nil
}

func (x *Message) GetPingResponse() *PingResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_PingResponse); ok {
			return x.PingResponse
		}
	}
	return nil
}

type isMessage_Sum interface {
	isMessage_Sum()
}

type Message_PubKeyRequest struct {
	PubKeyRequest *PubKeyRequest `protobuf:"bytes,1,opt,name=pub_key_request,json=pubKeyRequest,proto3,oneof"`
}

type Message_PubKeyResponse struct {
	PubKeyResponse *PubKeyResponse `protobuf:"bytes,2,opt,name=pub_key_response,json=pubKeyResponse,proto3,oneof"`
}

type Message_SignVoteRequest struct {
	SignVoteRequest *SignVoteRequest `protobuf:"bytes,3,opt,name=sign_vote_request,json=signVoteRequest,proto3,oneof"`
}

type Message_SignedVoteResponse struct {
	SignedVoteResponse *SignedVoteResponse `protobuf:"bytes,4,opt,name=signed_vote_response,json=signedVoteResponse,proto3,oneof"`
}

type Message_SignProposalRequest struct {
	SignProposalRequest *SignProposalRequest `protobuf:"bytes,5,opt,name=sign_proposal_request,json=signProposalRequest,proto3,oneof"`
}

type Message_SignedProposalResponse struct {
	SignedProposalResponse *SignedProposalResponse `protobuf:"bytes,6,opt,name=signed_proposal_response,json=signedProposalResponse,proto3,oneof"`
}

type Message_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,7,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type Message_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,8,opt,name=ping_response,json=pingResponse,proto3,oneof"`
}

func (*Message_PubKeyRequest) isMessage_Sum() {}

func (*Message_PubKeyResponse) isMessage_Sum() {}

func (*Message_SignVoteRequest) isMessage_Sum() {}

func (*Message_SignedVoteResponse) isMessage_Sum() {}

func (*Message_SignProposalRequest) isMessage_Sum() {}

func (*Message_SignedProposalResponse) isMessage_Sum() {}

func (*Message_PingRequest) isMessage_Sum() {}

func (*Message_PingResponse) isMessage_Sum() {}

var File_tendermint_privval_types_proto protoreflect.FileDescriptor

const file_tendermint_privval_types_proto_rawDesc = "" +
	"\n" +
	"\x1etendermint/privval/types.proto\x12\x12tendermint.privval\x1a\x1ctendermint/crypto/keys.proto\x1a\x1ctendermint/types/types.proto\x1a\x14gogoproto/gogo.proto\"I\n" +
	"\x11RemoteSignerError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"*\n" +
	"\rPubKeyRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"\x8a\x01\n" +
	"\x0ePubKeyResponse\x12;\n" +
	"\apub_key\x18\x01 \x01(\v2\x1c.tendermint.crypto.PublicKeyB\x04\xc8\xde\x1f\x00R\x06pubKey\x12;\n" +
	"\x05error\x18\x02 \x01(\v2%.tendermint.privval.RemoteSignerErrorR\x05error\"X\n" +
	"\x0fSignVoteRequest\x12*\n" +
	"\x04vote\x18\x01 \x01(\v2\x16.tendermint.types.VoteR\x04vote\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\"\x83\x01\n" +
	"\x12SignedVoteResponse\x120\n" +
	"\x04vote\x18\x01 \x01(\v2\x16.tendermint.types.VoteB\x04\xc8\xde\x1f\x00R\x04vote\x12;\n" +
	"\x05error\x18\x02 \x01(\v2%.tendermint.privval.RemoteSignerErrorR\x05error\"h\n" +
	"\x13SignProposalRequest\x126\n" +
	"\bproposal\x18\x01 \x01(\v2\x1a.tendermint.types.ProposalR\bproposal\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\"\x93\x01\n" +
	"\x16SignedProposalResponse\x12<\n" +
	"\bproposal\x18\x01 \x01(\v2\x1a.tendermint.types.ProposalB\x04\xc8\xde\x1f\x00R\bproposal\x12;\n" +
	"\x05error\x18\x02 \x01(\v2%.tendermint.privval.RemoteSignerErrorR\x05error\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\xb2\x05\n" +
	"\aMessage\x12K\n" +
	"\x0fpub_key_request\x18\x01 \x01(\v2!.tendermint.privval.PubKeyRequestH\x00R\rpubKeyRequest\x12N\n" +
	"\x10pub_key_response\x18\x02 \x01(\v2\".tendermint.privval.PubKeyResponseH\x00R\x0epubKeyResponse\x12Q\n" +
	"\x11sign_vote_request\x18\x03 \x01(\v2#.tendermint.privval.SignVoteRequestH\x00R\x0fsignVoteRequest\x12Z\n" +
	"\x14signed_vote_response\x18\x04 \x01(\v2&.tendermint.privval.SignedVoteResponseH\x00R\x12signedVoteResponse\x12]\n" +
	"\x15sign_proposal_request\x18\x05 \x01(\v2'.tendermint.privval.SignProposalRequestH\x00R\x13signProposalRequest\x12f\n" +
	"\x18signed_proposal_response\x18\x06 \x01(\v2*.tendermint.privval.SignedProposalResponseH\x00R\x16signedProposalResponse\x12D\n" +
	"\fping_request\x18\a \x01(\v2\x1f.tendermint.privval.PingRequestH\x00R\vpingRequest\x12G\n" +
	"\rping_response\x18\b \x01(\v2 .tendermint.privval.PingResponseH\x00R\fpingResponseB\x05\n" +
	"\x03sum*\xa8\x01\n" +
	"\x06Errors\x12\x12\n" +
	"\x0eERRORS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aERRORS_UNEXPECTED_RESPONSE\x10\x01\x12\x18\n" +
	"\x14ERRORS_NO_CONNECTION\x10\x02\x12\x1d\n" +
	"\x19ERRORS_CONNECTION_TIMEOUT\x10\x03\x12\x17\n" +
	"\x13ERRORS_READ_TIMEOUT\x10\x04\x12\x18\n" +
	"\x14ERRORS_WRITE_TIMEOUT\x10\x05B\xca\x01\n" +
	"\x16com.tendermint.privvalB\n" +
	"TypesProtoP\x01Z;github.com/fluentum-chain/fluentum/proto/tendermint/privval\xa2\x02\x03TPX\xaa\x02\x12Tendermint.Privval\xca\x02\x12Tendermint\\Privval\xe2\x02\x1eTendermint\\Privval\\GPBMetadata\xea\x02\x13Tendermint::Privvalb\x06proto3"

var (
	file_tendermint_privval_types_proto_rawDescOnce sync.Once
	file_tendermint_privval_types_proto_rawDescData []byte
)

func file_tendermint_privval_types_proto_rawDescGZIP() []byte {
	file_tendermint_privval_types_proto_rawDescOnce.Do(func() {
		file_tendermint_privval_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_privval_types_proto_rawDesc), len(file_tendermint_privval_types_proto_rawDesc)))
	})
	return file_tendermint_privval_types_proto_rawDescData
}

var file_tendermint_privval_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tendermint_privval_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tendermint_privval_types_proto_goTypes = []any{
	(Errors)(0),                    // 0: tendermint.privval.Errors
	(*RemoteSignerError)(nil),      // 1: tendermint.privval.RemoteSignerError
	(*PubKeyRequest)(nil),          // 2: tendermint.privval.PubKeyRequest
	(*PubKeyResponse)(nil),         // 3: tendermint.privval.PubKeyResponse
	(*SignVoteRequest)(nil),        // 4: tendermint.privval.SignVoteRequest
	(*SignedVoteResponse)(nil),     // 5: tendermint.privval.SignedVoteResponse
	(*SignProposalRequest)(nil),    // 6: tendermint.privval.SignProposalRequest
	(*SignedProposalResponse)(nil), // 7: tendermint.privval.SignedProposalResponse
	(*PingRequest)(nil),            // 8: tendermint.privval.PingRequest
	(*PingResponse)(nil),           // 9: tendermint.privval.PingResponse
	(*Message)(nil),                // 10: tendermint.privval.Message
	(*crypto.PublicKey)(nil),       // 11: tendermint.crypto.PublicKey
	(*types.Vote)(nil),             // 12: tendermint.types.Vote
	(*types.Proposal)(nil),         // 13: tendermint.types.Proposal
}
var file_tendermint_privval_types_proto_depIdxs = []int32{
	11, // 0: tendermint.privval.PubKeyResponse.pub_key:type_name -> tendermint.crypto.PublicKey
	1,  // 1: tendermint.privval.PubKeyResponse.error:type_name -> tendermint.privval.RemoteSignerError
	12, // 2: tendermint.privval.SignVoteRequest.vote:type_name -> tendermint.types.Vote
	12, // 3: tendermint.privval.SignedVoteResponse.vote:type_name -> tendermint.types.Vote
	1,  // 4: tendermint.privval.SignedVoteResponse.error:type_name -> tendermint.privval.RemoteSignerError
	13, // 5: tendermint.privval.SignProposalRequest.proposal:type_name -> tendermint.types.Proposal
	13, // 6: tendermint.privval.SignedProposalResponse.proposal:type_name -> tendermint.types.Proposal
	1,  // 7: tendermint.privval.SignedProposalResponse.error:type_name -> tendermint.privval.RemoteSignerError
	2,  // 8: tendermint.privval.Message.pub_key_request:type_name -> tendermint.privval.PubKeyRequest
	3,  // 9: tendermint.privval.Message.pub_key_response:type_name -> tendermint.privval.PubKeyResponse
	4,  // 10: tendermint.privval.Message.sign_vote_request:type_name -> tendermint.privval.SignVoteRequest
	5,  // 11: tendermint.privval.Message.signed_vote_response:type_name -> tendermint.privval.SignedVoteResponse
	6,  // 12: tendermint.privval.Message.sign_proposal_request:type_name -> tendermint.privval.SignProposalRequest
	7,  // 13: tendermint.privval.Message.signed_proposal_response:type_name -> tendermint.privval.SignedProposalResponse
	8,  // 14: tendermint.privval.Message.ping_request:type_name -> tendermint.privval.PingRequest
	9,  // 15: tendermint.privval.Message.ping_response:type_name -> tendermint.privval.PingResponse
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_tendermint_privval_types_proto_init() }
func file_tendermint_privval_types_proto_init() {
	if File_tendermint_privval_types_proto != nil {
		return
	}
	file_tendermint_privval_types_proto_msgTypes[9].OneofWrappers = []any{
		(*Message_PubKeyRequest)(nil),
		(*Message_PubKeyResponse)(nil),
		(*Message_SignVoteRequest)(nil),
		(*Message_SignedVoteResponse)(nil),
		(*Message_SignProposalRequest)(nil),
		(*Message_SignedProposalResponse)(nil),
		(*Message_PingRequest)(nil),
		(*Message_PingResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_privval_types_proto_rawDesc), len(file_tendermint_privval_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_privval_types_proto_goTypes,
		DependencyIndexes: file_tendermint_privval_types_proto_depIdxs,
		EnumInfos:         file_tendermint_privval_types_proto_enumTypes,
		MessageInfos:      file_tendermint_privval_types_proto_msgTypes,
	}.Build()
	File_tendermint_privval_types_proto = out.File
	file_tendermint_privval_types_proto_goTypes = nil
	file_tendermint_privval_types_proto_depIdxs = nil
}
