// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/store/types.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockStoreState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          int64                  `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Height        int64                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockStoreState) Reset() {
	*x = BlockStoreState{}
	mi := &file_tendermint_store_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockStoreState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockStoreState) ProtoMessage() {}

func (x *BlockStoreState) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_store_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockStoreState.ProtoReflect.Descriptor instead.
func (*BlockStoreState) Descriptor() ([]byte, []int) {
	return file_tendermint_store_types_proto_rawDescGZIP(), []int{0}
}

func (x *BlockStoreState) GetBase() int64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *BlockStoreState) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_tendermint_store_types_proto protoreflect.FileDescriptor

const file_tendermint_store_types_proto_rawDesc = "" +
	"\n" +
	"\x1ctendermint/store/types.proto\x12\x10tendermint.store\"=\n" +
	"\x0fBlockStoreState\x12\x12\n" +
	"\x04base\x18\x01 \x01(\x03R\x04base\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x03R\x06heightB\xbe\x01\n" +
	"\x14com.tendermint.storeB\n" +
	"TypesProtoP\x01Z9github.com/fluentum-chain/fluentum/proto/tendermint/store\xa2\x02\x03TSX\xaa\x02\x10Tendermint.Store\xca\x02\x10Tendermint\\Store\xe2\x02\x1cTendermint\\Store\\GPBMetadata\xea\x02\x11Tendermint::Storeb\x06proto3"

var (
	file_tendermint_store_types_proto_rawDescOnce sync.Once
	file_tendermint_store_types_proto_rawDescData []byte
)

func file_tendermint_store_types_proto_rawDescGZIP() []byte {
	file_tendermint_store_types_proto_rawDescOnce.Do(func() {
		file_tendermint_store_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_store_types_proto_rawDesc), len(file_tendermint_store_types_proto_rawDesc)))
	})
	return file_tendermint_store_types_proto_rawDescData
}

var file_tendermint_store_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tendermint_store_types_proto_goTypes = []any{
	(*BlockStoreState)(nil), // 0: tendermint.store.BlockStoreState
}
var file_tendermint_store_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tendermint_store_types_proto_init() }
func file_tendermint_store_types_proto_init() {
	if File_tendermint_store_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_store_types_proto_rawDesc), len(file_tendermint_store_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_store_types_proto_goTypes,
		DependencyIndexes: file_tendermint_store_types_proto_depIdxs,
		MessageInfos:      file_tendermint_store_types_proto_msgTypes,
	}.Build()
	File_tendermint_store_types_proto = out.File
	file_tendermint_store_types_proto_goTypes = nil
	file_tendermint_store_types_proto_depIdxs = nil
}
