// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/statesync/types.proto

package statesync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sum:
	//
	//	*Message_SnapshotsRequest
	//	*Message_SnapshotsResponse
	//	*Message_ChunkRequest
	//	*Message_ChunkResponse
	Sum           isMessage_Sum `protobuf_oneof:"sum"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_tendermint_statesync_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_statesync_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_tendermint_statesync_types_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSum() isMessage_Sum {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *Message) GetSnapshotsRequest() *SnapshotsRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_SnapshotsRequest); ok {
			return x.SnapshotsRequest
		}
	}
	return nil
}

func (x *Message) GetSnapshotsResponse() *SnapshotsResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_SnapshotsResponse); ok {
			return x.SnapshotsResponse
		}
	}
	return nil
}

func (x *Message) GetChunkRequest() *ChunkRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_ChunkRequest); ok {
			return x.ChunkRequest
		}
	}
	return nil
}

func (x *Message) GetChunkResponse() *ChunkResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_ChunkResponse); ok {
			return x.ChunkResponse
		}
	}
	return nil
}

type isMessage_Sum interface {
	isMessage_Sum()
}

type Message_SnapshotsRequest struct {
	SnapshotsRequest *SnapshotsRequest `protobuf:"bytes,1,opt,name=snapshots_request,json=snapshotsRequest,proto3,oneof"`
}

type Message_SnapshotsResponse struct {
	SnapshotsResponse *SnapshotsResponse `protobuf:"bytes,2,opt,name=snapshots_response,json=snapshotsResponse,proto3,oneof"`
}

type Message_ChunkRequest struct {
	ChunkRequest *ChunkRequest `protobuf:"bytes,3,opt,name=chunk_request,json=chunkRequest,proto3,oneof"`
}

type Message_ChunkResponse struct {
	ChunkResponse *ChunkResponse `protobuf:"bytes,4,opt,name=chunk_response,json=chunkResponse,proto3,oneof"`
}

func (*Message_SnapshotsRequest) isMessage_Sum() {}

func (*Message_SnapshotsResponse) isMessage_Sum() {}

func (*Message_ChunkRequest) isMessage_Sum() {}

func (*Message_ChunkResponse) isMessage_Sum() {}

type SnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotsRequest) Reset() {
	*x = SnapshotsRequest{}
	mi := &file_tendermint_statesync_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotsRequest) ProtoMessage() {}

func (x *SnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_statesync_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotsRequest.ProtoReflect.Descriptor instead.
func (*SnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_statesync_types_proto_rawDescGZIP(), []int{1}
}

type SnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Format        uint32                 `protobuf:"varint,2,opt,name=format,proto3" json:"format,omitempty"`
	Chunks        uint32                 `protobuf:"varint,3,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Hash          []byte                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotsResponse) Reset() {
	*x = SnapshotsResponse{}
	mi := &file_tendermint_statesync_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotsResponse) ProtoMessage() {}

func (x *SnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_statesync_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotsResponse.ProtoReflect.Descriptor instead.
func (*SnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_statesync_types_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotsResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SnapshotsResponse) GetFormat() uint32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *SnapshotsResponse) GetChunks() uint32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *SnapshotsResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *SnapshotsResponse) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Format        uint32                 `protobuf:"varint,2,opt,name=format,proto3" json:"format,omitempty"`
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_tendermint_statesync_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_statesync_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_statesync_types_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChunkRequest) GetFormat() uint32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *ChunkRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Format        uint32                 `protobuf:"varint,2,opt,name=format,proto3" json:"format,omitempty"`
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Missing       bool                   `protobuf:"varint,5,opt,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	mi := &file_tendermint_statesync_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_statesync_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_statesync_types_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ChunkResponse) GetFormat() uint32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *ChunkResponse) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChunkResponse) GetMissing() bool {
	if x != nil {
		return x.Missing
	}
	return false
}

var File_tendermint_statesync_types_proto protoreflect.FileDescriptor

const file_tendermint_statesync_types_proto_rawDesc = "" +
	"\n" +
	" tendermint/statesync/types.proto\x12\x14tendermint.statesync\"\xda\x02\n" +
	"\aMessage\x12U\n" +
	"\x11snapshots_request\x18\x01 \x01(\v2&.tendermint.statesync.SnapshotsRequestH\x00R\x10snapshotsRequest\x12X\n" +
	"\x12snapshots_response\x18\x02 \x01(\v2'.tendermint.statesync.SnapshotsResponseH\x00R\x11snapshotsResponse\x12I\n" +
	"\rchunk_request\x18\x03 \x01(\v2\".tendermint.statesync.ChunkRequestH\x00R\fchunkRequest\x12L\n" +
	"\x0echunk_response\x18\x04 \x01(\v2#.tendermint.statesync.ChunkResponseH\x00R\rchunkResponseB\x05\n" +
	"\x03sum\"\x12\n" +
	"\x10SnapshotsRequest\"\x8b\x01\n" +
	"\x11SnapshotsResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x16\n" +
	"\x06format\x18\x02 \x01(\rR\x06format\x12\x16\n" +
	"\x06chunks\x18\x03 \x01(\rR\x06chunks\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\fR\bmetadata\"T\n" +
	"\fChunkRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x16\n" +
	"\x06format\x18\x02 \x01(\rR\x06format\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\"\x85\x01\n" +
	"\rChunkResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x16\n" +
	"\x06format\x18\x02 \x01(\rR\x06format\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk\x12\x18\n" +
	"\amissing\x18\x05 \x01(\bR\amissingB\xd6\x01\n" +
	"\x18com.tendermint.statesyncB\n" +
	"TypesProtoP\x01Z=github.com/fluentum-chain/fluentum/proto/tendermint/statesync\xa2\x02\x03TSX\xaa\x02\x14Tendermint.Statesync\xca\x02\x14Tendermint\\Statesync\xe2\x02 Tendermint\\Statesync\\GPBMetadata\xea\x02\x15Tendermint::Statesyncb\x06proto3"

var (
	file_tendermint_statesync_types_proto_rawDescOnce sync.Once
	file_tendermint_statesync_types_proto_rawDescData []byte
)

func file_tendermint_statesync_types_proto_rawDescGZIP() []byte {
	file_tendermint_statesync_types_proto_rawDescOnce.Do(func() {
		file_tendermint_statesync_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_statesync_types_proto_rawDesc), len(file_tendermint_statesync_types_proto_rawDesc)))
	})
	return file_tendermint_statesync_types_proto_rawDescData
}

var file_tendermint_statesync_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tendermint_statesync_types_proto_goTypes = []any{
	(*Message)(nil),           // 0: tendermint.statesync.Message
	(*SnapshotsRequest)(nil),  // 1: tendermint.statesync.SnapshotsRequest
	(*SnapshotsResponse)(nil), // 2: tendermint.statesync.SnapshotsResponse
	(*ChunkRequest)(nil),      // 3: tendermint.statesync.ChunkRequest
	(*ChunkResponse)(nil),     // 4: tendermint.statesync.ChunkResponse
}
var file_tendermint_statesync_types_proto_depIdxs = []int32{
	1, // 0: tendermint.statesync.Message.snapshots_request:type_name -> tendermint.statesync.SnapshotsRequest
	2, // 1: tendermint.statesync.Message.snapshots_response:type_name -> tendermint.statesync.SnapshotsResponse
	3, // 2: tendermint.statesync.Message.chunk_request:type_name -> tendermint.statesync.ChunkRequest
	4, // 3: tendermint.statesync.Message.chunk_response:type_name -> tendermint.statesync.ChunkResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tendermint_statesync_types_proto_init() }
func file_tendermint_statesync_types_proto_init() {
	if File_tendermint_statesync_types_proto != nil {
		return
	}
	file_tendermint_statesync_types_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_SnapshotsRequest)(nil),
		(*Message_SnapshotsResponse)(nil),
		(*Message_ChunkRequest)(nil),
		(*Message_ChunkResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_statesync_types_proto_rawDesc), len(file_tendermint_statesync_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_statesync_types_proto_goTypes,
		DependencyIndexes: file_tendermint_statesync_types_proto_depIdxs,
		MessageInfos:      file_tendermint_statesync_types_proto_msgTypes,
	}.Build()
	File_tendermint_statesync_types_proto = out.File
	file_tendermint_statesync_types_proto_goTypes = nil
	file_tendermint_statesync_types_proto_depIdxs = nil
}
