// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/blockchain/types.proto

package blockchain

import (
	types "github.com/fluentum-chain/fluentum/proto/tendermint/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockRequest requests a block for a specific height
type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_tendermint_blockchain_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_blockchain_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_blockchain_types_proto_rawDescGZIP(), []int{0}
}

func (x *BlockRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// NoBlockResponse informs the node that the peer does not have block at the requested height
type NoBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoBlockResponse) Reset() {
	*x = NoBlockResponse{}
	mi := &file_tendermint_blockchain_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoBlockResponse) ProtoMessage() {}

func (x *NoBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_blockchain_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoBlockResponse.ProtoReflect.Descriptor instead.
func (*NoBlockResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_blockchain_types_proto_rawDescGZIP(), []int{1}
}

func (x *NoBlockResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// BlockResponse returns block to the requested
type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *types.Block           `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_tendermint_blockchain_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_blockchain_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_blockchain_types_proto_rawDescGZIP(), []int{2}
}

func (x *BlockResponse) GetBlock() *types.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// StatusRequest requests the status of a peer.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_tendermint_blockchain_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_blockchain_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_tendermint_blockchain_types_proto_rawDescGZIP(), []int{3}
}

// StatusResponse is a peer response to inform their status.
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Base          int64                  `protobuf:"varint,2,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_tendermint_blockchain_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_blockchain_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_tendermint_blockchain_types_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StatusResponse) GetBase() int64 {
	if x != nil {
		return x.Base
	}
	return 0
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sum:
	//
	//	*Message_BlockRequest
	//	*Message_NoBlockResponse
	//	*Message_BlockResponse
	//	*Message_StatusRequest
	//	*Message_StatusResponse
	Sum           isMessage_Sum `protobuf_oneof:"sum"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_tendermint_blockchain_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_blockchain_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_tendermint_blockchain_types_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetSum() isMessage_Sum {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *Message) GetBlockRequest() *BlockRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_BlockRequest); ok {
			return x.BlockRequest
		}
	}
	return nil
}

func (x *Message) GetNoBlockResponse() *NoBlockResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_NoBlockResponse); ok {
			return x.NoBlockResponse
		}
	}
	return nil
}

func (x *Message) GetBlockResponse() *BlockResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_BlockResponse); ok {
			return x.BlockResponse
		}
	}
	return nil
}

func (x *Message) GetStatusRequest() *StatusRequest {
	if x != nil {
		if x, ok := x.Sum.(*Message_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

func (x *Message) GetStatusResponse() *StatusResponse {
	if x != nil {
		if x, ok := x.Sum.(*Message_StatusResponse); ok {
			return x.StatusResponse
		}
	}
	return nil
}

type isMessage_Sum interface {
	isMessage_Sum()
}

type Message_BlockRequest struct {
	BlockRequest *BlockRequest `protobuf:"bytes,1,opt,name=block_request,json=blockRequest,proto3,oneof"`
}

type Message_NoBlockResponse struct {
	NoBlockResponse *NoBlockResponse `protobuf:"bytes,2,opt,name=no_block_response,json=noBlockResponse,proto3,oneof"`
}

type Message_BlockResponse struct {
	BlockResponse *BlockResponse `protobuf:"bytes,3,opt,name=block_response,json=blockResponse,proto3,oneof"`
}

type Message_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,4,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

type Message_StatusResponse struct {
	StatusResponse *StatusResponse `protobuf:"bytes,5,opt,name=status_response,json=statusResponse,proto3,oneof"`
}

func (*Message_BlockRequest) isMessage_Sum() {}

func (*Message_NoBlockResponse) isMessage_Sum() {}

func (*Message_BlockResponse) isMessage_Sum() {}

func (*Message_StatusRequest) isMessage_Sum() {}

func (*Message_StatusResponse) isMessage_Sum() {}

var File_tendermint_blockchain_types_proto protoreflect.FileDescriptor

const file_tendermint_blockchain_types_proto_rawDesc = "" +
	"\n" +
	"!tendermint/blockchain/types.proto\x12\x15tendermint.blockchain\x1a\x1ctendermint/types/block.proto\"&\n" +
	"\fBlockRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\")\n" +
	"\x0fNoBlockResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\">\n" +
	"\rBlockResponse\x12-\n" +
	"\x05block\x18\x01 \x01(\v2\x17.tendermint.types.BlockR\x05block\"\x0f\n" +
	"\rStatusRequest\"<\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x12\n" +
	"\x04base\x18\x02 \x01(\x03R\x04base\"\xa2\x03\n" +
	"\aMessage\x12J\n" +
	"\rblock_request\x18\x01 \x01(\v2#.tendermint.blockchain.BlockRequestH\x00R\fblockRequest\x12T\n" +
	"\x11no_block_response\x18\x02 \x01(\v2&.tendermint.blockchain.NoBlockResponseH\x00R\x0fnoBlockResponse\x12M\n" +
	"\x0eblock_response\x18\x03 \x01(\v2$.tendermint.blockchain.BlockResponseH\x00R\rblockResponse\x12M\n" +
	"\x0estatus_request\x18\x04 \x01(\v2$.tendermint.blockchain.StatusRequestH\x00R\rstatusRequest\x12P\n" +
	"\x0fstatus_response\x18\x05 \x01(\v2%.tendermint.blockchain.StatusResponseH\x00R\x0estatusResponseB\x05\n" +
	"\x03sumB\xdc\x01\n" +
	"\x19com.tendermint.blockchainB\n" +
	"TypesProtoP\x01Z>github.com/fluentum-chain/fluentum/proto/tendermint/blockchain\xa2\x02\x03TBX\xaa\x02\x15Tendermint.Blockchain\xca\x02\x15Tendermint\\Blockchain\xe2\x02!Tendermint\\Blockchain\\GPBMetadata\xea\x02\x16Tendermint::Blockchainb\x06proto3"

var (
	file_tendermint_blockchain_types_proto_rawDescOnce sync.Once
	file_tendermint_blockchain_types_proto_rawDescData []byte
)

func file_tendermint_blockchain_types_proto_rawDescGZIP() []byte {
	file_tendermint_blockchain_types_proto_rawDescOnce.Do(func() {
		file_tendermint_blockchain_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_blockchain_types_proto_rawDesc), len(file_tendermint_blockchain_types_proto_rawDesc)))
	})
	return file_tendermint_blockchain_types_proto_rawDescData
}

var file_tendermint_blockchain_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tendermint_blockchain_types_proto_goTypes = []any{
	(*BlockRequest)(nil),    // 0: tendermint.blockchain.BlockRequest
	(*NoBlockResponse)(nil), // 1: tendermint.blockchain.NoBlockResponse
	(*BlockResponse)(nil),   // 2: tendermint.blockchain.BlockResponse
	(*StatusRequest)(nil),   // 3: tendermint.blockchain.StatusRequest
	(*StatusResponse)(nil),  // 4: tendermint.blockchain.StatusResponse
	(*Message)(nil),         // 5: tendermint.blockchain.Message
	(*types.Block)(nil),     // 6: tendermint.types.Block
}
var file_tendermint_blockchain_types_proto_depIdxs = []int32{
	6, // 0: tendermint.blockchain.BlockResponse.block:type_name -> tendermint.types.Block
	0, // 1: tendermint.blockchain.Message.block_request:type_name -> tendermint.blockchain.BlockRequest
	1, // 2: tendermint.blockchain.Message.no_block_response:type_name -> tendermint.blockchain.NoBlockResponse
	2, // 3: tendermint.blockchain.Message.block_response:type_name -> tendermint.blockchain.BlockResponse
	3, // 4: tendermint.blockchain.Message.status_request:type_name -> tendermint.blockchain.StatusRequest
	4, // 5: tendermint.blockchain.Message.status_response:type_name -> tendermint.blockchain.StatusResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tendermint_blockchain_types_proto_init() }
func file_tendermint_blockchain_types_proto_init() {
	if File_tendermint_blockchain_types_proto != nil {
		return
	}
	file_tendermint_blockchain_types_proto_msgTypes[5].OneofWrappers = []any{
		(*Message_BlockRequest)(nil),
		(*Message_NoBlockResponse)(nil),
		(*Message_BlockResponse)(nil),
		(*Message_StatusRequest)(nil),
		(*Message_StatusResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_blockchain_types_proto_rawDesc), len(file_tendermint_blockchain_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_blockchain_types_proto_goTypes,
		DependencyIndexes: file_tendermint_blockchain_types_proto_depIdxs,
		MessageInfos:      file_tendermint_blockchain_types_proto_msgTypes,
	}.Build()
	File_tendermint_blockchain_types_proto = out.File
	file_tendermint_blockchain_types_proto_goTypes = nil
	file_tendermint_blockchain_types_proto_depIdxs = nil
}
