[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.5.0"
cw-storage-plus = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0" 