// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/libs/bits/types.proto

package bits

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BitArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bits          int64                  `protobuf:"varint,1,opt,name=bits,proto3" json:"bits,omitempty"`
	Elems         []uint64               `protobuf:"varint,2,rep,packed,name=elems,proto3" json:"elems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitArray) Reset() {
	*x = BitArray{}
	mi := &file_tendermint_libs_bits_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitArray) ProtoMessage() {}

func (x *BitArray) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_libs_bits_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitArray.ProtoReflect.Descriptor instead.
func (*BitArray) Descriptor() ([]byte, []int) {
	return file_tendermint_libs_bits_types_proto_rawDescGZIP(), []int{0}
}

func (x *BitArray) GetBits() int64 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *BitArray) GetElems() []uint64 {
	if x != nil {
		return x.Elems
	}
	return nil
}

var File_tendermint_libs_bits_types_proto protoreflect.FileDescriptor

const file_tendermint_libs_bits_types_proto_rawDesc = "" +
	"\n" +
	" tendermint/libs/bits/types.proto\x12\x14tendermint.libs.bits\"4\n" +
	"\bBitArray\x12\x12\n" +
	"\x04bits\x18\x01 \x01(\x03R\x04bits\x12\x14\n" +
	"\x05elems\x18\x02 \x03(\x04R\x05elemsB\xd7\x01\n" +
	"\x18com.tendermint.libs.bitsB\n" +
	"TypesProtoP\x01Z=github.com/fluentum-chain/fluentum/proto/tendermint/libs/bits\xa2\x02\x03TLB\xaa\x02\x14Tendermint.Libs.Bits\xca\x02\x14Tendermint\\Libs\\Bits\xe2\x02 Tendermint\\Libs\\Bits\\GPBMetadata\xea\x02\x16Tendermint::Libs::Bitsb\x06proto3"

var (
	file_tendermint_libs_bits_types_proto_rawDescOnce sync.Once
	file_tendermint_libs_bits_types_proto_rawDescData []byte
)

func file_tendermint_libs_bits_types_proto_rawDescGZIP() []byte {
	file_tendermint_libs_bits_types_proto_rawDescOnce.Do(func() {
		file_tendermint_libs_bits_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_libs_bits_types_proto_rawDesc), len(file_tendermint_libs_bits_types_proto_rawDesc)))
	})
	return file_tendermint_libs_bits_types_proto_rawDescData
}

var file_tendermint_libs_bits_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tendermint_libs_bits_types_proto_goTypes = []any{
	(*BitArray)(nil), // 0: tendermint.libs.bits.BitArray
}
var file_tendermint_libs_bits_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tendermint_libs_bits_types_proto_init() }
func file_tendermint_libs_bits_types_proto_init() {
	if File_tendermint_libs_bits_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_libs_bits_types_proto_rawDesc), len(file_tendermint_libs_bits_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_libs_bits_types_proto_goTypes,
		DependencyIndexes: file_tendermint_libs_bits_types_proto_depIdxs,
		MessageInfos:      file_tendermint_libs_bits_types_proto_msgTypes,
	}.Build()
	File_tendermint_libs_bits_types_proto = out.File
	file_tendermint_libs_bits_types_proto_goTypes = nil
	file_tendermint_libs_bits_types_proto_depIdxs = nil
}
