#!/bin/bash

# Fix proto-related issues
# This script fixes missing proto files, incorrect import paths, and outdated buf.lock

set -e

# Change to the project root directory
cd "$(dirname "$0")/.."

echo "Fixing proto-related issues..."

# 1. Create missing third_party/proto directory structure
echo "Creating missing third_party/proto directory structure..."
mkdir -p third_party/proto/gogoproto
mkdir -p third_party/proto/google/protobuf

# 2. Create missing gogoproto/gogo.proto file
cat > third_party/proto/gogoproto/gogo.proto << 'EOF'
syntax = "proto2";
package gogoproto;

import "google/protobuf/descriptor.proto";

option go_package = "github.com/gogo/protobuf/gogoproto";

extend google.protobuf.FieldOptions {
  optional bool nullable = 65001 [default = true];
}

extend google.protobuf.MessageOptions {
  optional bool marshaler = 64017 [default = false];
  optional bool unmarshaler = 64018 [default = false];
}

extend google.protobuf.EnumOptions {
  optional bool enumvalue_customname = 62021 [default = false];
}

extend google.protobuf.FieldOptions {
  optional bool stdtime = 65002 [default = false];
}
EOF

# 3. Update go_package paths in proto files
echo "Updating go_package paths in proto files..."

# Function to update go_package in a proto file
update_go_package() {
    local file="$1"
    local old_package="$2"
    local new_package="$3"
    
    if [ -f "$file" ]; then
        echo "Updating $file..."
        sed -i "s|option go_package = \"$old_package\";|option go_package = \"$new_package\";|g" "$file"
    fi
}

# Update go_package paths for all proto files
update_go_package "proto/tendermint/abci/types.proto" \
    "github.com/tendermint/tendermint/abci/types" \
    "github.com/fluentum-chain/fluentum/proto/tendermint/abci"

update_go_package "proto/tendermint/crypto/proof.proto" \
    "github.com/tendermint/tendermint/proto/tendermint/crypto" \
    "github.com/fluentum-chain/fluentum/proto/tendermint/crypto"

update_go_package "proto/tendermint/crypto/keys.proto" \
    "github.com/tendermint/tendermint/proto/tendermint/crypto" \
    "github.com/fluentum-chain/fluentum/proto/tendermint/crypto"

update_go_package "proto/tendermint/types/types.proto" \
    "github.com/tendermint/tendermint/proto/tendermint/types" \
    "github.com/fluentum-chain/fluentum/proto/tendermint/types"

# 4. Update buf.lock with correct dependencies
echo "Updating buf.lock with correct dependencies..."
cd proto
if command -v buf &> /dev/null; then
    echo "Running buf mod update..."
    buf mod update
else
    echo "buf not found, updating buf.lock manually..."
    cat > buf.lock << 'EOF'
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: gogo
    repository: protobuf
    commit: 4df00b267f944190a229ce3695781e99
  - remote: buf.build
    owner: cosmos
    repository: cosmos-proto
    commit: 8c5495d3c7e3b3b3c3c3c3c3c3c3c3c3c3c3c3c3
  - remote: buf.build
    owner: cosmos
    repository: gogo-proto
    commit: 8c5495d3c7e3b3b3c3c3c3c3c3c3c3c3c3c3c3c3
EOF
fi
cd ..

echo "Proto issues fixed successfully!"
echo ""
echo "Next steps:"
echo "1. Run: ./scripts/generate_proto_buf.sh"
echo "2. Or run: cd proto && buf generate" 