// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tendermint/version/types.proto

package version

import (
	_ "github.com/fluentum-chain/fluentum/proto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// App includes the protocol and software version for the application.
// This information is included in ResponseInfo. The App.Protocol can be
// updated in ResponseEndBlock.
type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      uint64                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Software      string                 `protobuf:"bytes,2,opt,name=software,proto3" json:"software,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_tendermint_version_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_version_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_tendermint_version_types_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetProtocol() uint64 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *App) GetSoftware() string {
	if x != nil {
		return x.Software
	}
	return ""
}

// Consensus captures the consensus rules for processing a block in the blockchain,
// including all blockchain data structures and the rules of the application's
// state transition machine.
type Consensus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         uint64                 `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	App           uint64                 `protobuf:"varint,2,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consensus) Reset() {
	*x = Consensus{}
	mi := &file_tendermint_version_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consensus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consensus) ProtoMessage() {}

func (x *Consensus) ProtoReflect() protoreflect.Message {
	mi := &file_tendermint_version_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consensus.ProtoReflect.Descriptor instead.
func (*Consensus) Descriptor() ([]byte, []int) {
	return file_tendermint_version_types_proto_rawDescGZIP(), []int{1}
}

func (x *Consensus) GetBlock() uint64 {
	if x != nil {
		return x.Block
	}
	return 0
}

func (x *Consensus) GetApp() uint64 {
	if x != nil {
		return x.App
	}
	return 0
}

var File_tendermint_version_types_proto protoreflect.FileDescriptor

const file_tendermint_version_types_proto_rawDesc = "" +
	"\n" +
	"\x1etendermint/version/types.proto\x12\x12tendermint.version\x1a\x14gogoproto/gogo.proto\"=\n" +
	"\x03App\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\x04R\bprotocol\x12\x1a\n" +
	"\bsoftware\x18\x02 \x01(\tR\bsoftware\"9\n" +
	"\tConsensus\x12\x14\n" +
	"\x05block\x18\x01 \x01(\x04R\x05block\x12\x10\n" +
	"\x03app\x18\x02 \x01(\x04R\x03app:\x04\xe8\xa0\x1f\x01B\xca\x01\n" +
	"\x16com.tendermint.versionB\n" +
	"TypesProtoP\x01Z;github.com/fluentum-chain/fluentum/proto/tendermint/version\xa2\x02\x03TVX\xaa\x02\x12Tendermint.Version\xca\x02\x12Tendermint\\Version\xe2\x02\x1eTendermint\\Version\\GPBMetadata\xea\x02\x13Tendermint::Versionb\x06proto3"

var (
	file_tendermint_version_types_proto_rawDescOnce sync.Once
	file_tendermint_version_types_proto_rawDescData []byte
)

func file_tendermint_version_types_proto_rawDescGZIP() []byte {
	file_tendermint_version_types_proto_rawDescOnce.Do(func() {
		file_tendermint_version_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tendermint_version_types_proto_rawDesc), len(file_tendermint_version_types_proto_rawDesc)))
	})
	return file_tendermint_version_types_proto_rawDescData
}

var file_tendermint_version_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tendermint_version_types_proto_goTypes = []any{
	(*App)(nil),       // 0: tendermint.version.App
	(*Consensus)(nil), // 1: tendermint.version.Consensus
}
var file_tendermint_version_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tendermint_version_types_proto_init() }
func file_tendermint_version_types_proto_init() {
	if File_tendermint_version_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tendermint_version_types_proto_rawDesc), len(file_tendermint_version_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tendermint_version_types_proto_goTypes,
		DependencyIndexes: file_tendermint_version_types_proto_depIdxs,
		MessageInfos:      file_tendermint_version_types_proto_msgTypes,
	}.Build()
	File_tendermint_version_types_proto = out.File
	file_tendermint_version_types_proto_goTypes = nil
	file_tendermint_version_types_proto_depIdxs = nil
}
